### ISSUE TITLE
Enregistrement de certains fichiers sans nom

### ISSUE THREAD

**Issue by ghost** [EliseChap/PDL_2018-2019_GR1#6]
Le nom des fichiers CSV doivent prendre le nom du tableau extrait , ou "Wikimatrix.csv" si le tableau n'a pas de nom.
Or ici, quand il n'y a pas de nom de tableau, les fichiers html prennent le nom "table" + chiffre et en wikicode "WithoutTitle" + chiffre.

**Comment by ghost** [comment]
Cette issue n'est pas possible à résoudre, car le nom des fichiers est dépendant de Wikipédia et par conséquent pas possible à modifier.

**Comment by MaellaGheraia** [comment]
Le nom du fichier CSV est celui du titre du tableau dans la page Wikipédia. Si le tableau n'a pas de nom, l'extracteur affecte au fichier CSV un nom par défaut.
