### ISSUE TITLE
Erreur ClassNotFoundException: javax.xml.bind.PropertyException 

### ISSUE THREAD

**Issue by MaellaGheraia** [EliseChap/PDL_2018-2019_GR1#8]
Erreur ClassNotFoundException: javax.xml.bind.PropertyException. L'erreur se produit, au moment de l'extraction, sur certaines machines mais pas toutes.

**Comment by ghost** [comment]
https://github.com/EliseChap/PDL_2018-2019_GR1/commit/541eb5977514fbf29da637137904e6030f245d65
